"""empty message

Revision ID: 61c0955c5d22
Revises: 
Create Date: 2022-06-19 05:59:17.277333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c0955c5d22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=64), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_completed'), 'todo', ['completed'], unique=False)
    op.create_index(op.f('ix_todo_details'), 'todo', ['details'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_details'), table_name='todo')
    op.drop_index(op.f('ix_todo_completed'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
