"""empty message

Revision ID: c527a8be66b0
Revises: 98cf2ba46057
Create Date: 2022-06-18 13:27:37.766158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c527a8be66b0'
down_revision = '98cf2ba46057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_details'), 'todo', ['details'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_details'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
