# Generated by Django 4.0.5 on 2022-06-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('task_role', models.CharField(max_length=30)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('done_task', models.BooleanField()),
                ('number_hour', models.IntegerField()),
            ],
        ),
    ]
