# Generated by Django 4.0.5 on 2022-07-01 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_post_released_date_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.person')),
                ('email', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 5, 49, 47, 552828)),
        ),
    ]
